// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awyiyumcjrzfehfjpqyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3eWl5dW1janJ6ZmVoZmpwcXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjU0NzksImV4cCI6MjA1OTEwMTQ3OX0.UPV4KGhxoxGnumoyA6V6X5_cgjJSA5P9okB098Y2tdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);